services:
  database:
    image: postgres:17-alpine@sha256:dc17045ccfd343b49600570ea734b9c4991cf1c3f3302e67df51e3b402dd55c4
    container_name: Database_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_db_password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine@sha256:c9d92d840fd011c908f040592857c724ae6d877f2aba5c40ad963276507386b2
    container_name: Cache_dev
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-my_secure_password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  postgres_data_dev:
  redis_data_dev:
